language: python
sudo: false
cache: pip

python:
  - "3.5"
  - "2.7"

env:
  - DJANGO="django>=1.11,<1.12"
  - DJANGO="django>=2.0,<2.2"

matrix:
  exclude:
   - python: "2.7"
     env: DJANGO="django>=2.0,<2.2"

branches:
  only:
    - master
    - gsoc2019

before_install:
  - pip install -U pip wheel setuptools
  - pip install --no-cache-dir -U -r requirements-test.txt
  - openwisp-utils-qa-checks --migration-path ./django_netjsonconfig/migrations/
  - npm install -g jslint
  - jslint django_netjsonconfig/static/django-netjsonconfig/js/*.js

install:
  - pip install $DJANGO
  - python setup.py -q develop

script:
  - coverage run --source=django_netjsonconfig runtests.py
  - if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then ./tests/manage.py makemigrations --dry-run | grep "No changes detected"; fi

after_success:
  coveralls
